"""Add more fields summary

Revision ID: 1f72950a73aa
Revises: 243b930133af
Create Date: 2025-04-30 10:51:29.798065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f72950a73aa'
down_revision: Union[str, None] = '243b930133af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_summaries', sa.Column('suggestions', sa.String(), nullable=True))
    op.add_column('session_summaries', sa.Column('progress_observations', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('session_summaries', 'progress_observations')
    op.drop_column('session_summaries', 'suggestions')
    # ### end Alembic commands ### 