"""add chat models

Revision ID: d3f0f7d1f1e2
Revises: initial
Create Date: 2025-04-15 11:07:56.806775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f0f7d1f1e2'
down_revision: Union[str, None] = 'initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('timestamp', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('sentiment', sa.String(), nullable=True))
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('chat_messages', 'is_user',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.drop_column('chat_messages', 'created_at')
    op.add_column('chat_sessions', sa.Column('started_at', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('ended_at', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('sentiment_score', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.drop_column('chat_sessions', 'updated_at')
    op.drop_column('chat_sessions', 'created_at')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('chat_sessions', sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('chat_sessions', sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('chat_sessions', 'is_active')
    op.drop_column('chat_sessions', 'risk_level')
    op.drop_column('chat_sessions', 'sentiment_score')
    op.drop_column('chat_sessions', 'ended_at')
    op.drop_column('chat_sessions', 'started_at')
    op.add_column('chat_messages', sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.alter_column('chat_messages', 'is_user',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('chat_messages', 'sentiment')
    op.drop_column('chat_messages', 'timestamp')
    # ### end Alembic commands ### 